/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SuperCalculadoraSwing;

/**
 *
 * @author Loja
 */
public class SuperCalculadoraS extends javax.swing.JFrame {

    /**
     * Creates new form SuperCalculadoraS
     */
    public SuperCalculadoraS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spnValor = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtResto = new javax.swing.JLabel();
        txtElevado = new javax.swing.JLabel();
        txtRaizQuad = new javax.swing.JLabel();
        txtRaizCub = new javax.swing.JLabel();
        txtAbso = new javax.swing.JLabel();
        lblResto = new javax.swing.JLabel();
        lblElevado = new javax.swing.JLabel();
        lblRaizQuad = new javax.swing.JLabel();
        lblRaizCub = new javax.swing.JLabel();
        lblAbso = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Super Calculadora");
        jLabel1.setAlignmentY(0.0F);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Informe um valor:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/calculo1.png"))); // NOI18N
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/calculadora1.png"))); // NOI18N

        txtResto.setToolTipText("");

        txtElevado.setToolTipText("");

        txtRaizQuad.setToolTipText("");

        txtRaizCub.setToolTipText("");

        txtAbso.setToolTipText("");

        lblResto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblResto.setForeground(new java.awt.Color(0, 51, 255));
        lblResto.setToolTipText("");

        lblElevado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblElevado.setForeground(new java.awt.Color(0, 51, 255));
        lblElevado.setToolTipText("");

        lblRaizQuad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblRaizQuad.setForeground(new java.awt.Color(0, 51, 255));
        lblRaizQuad.setToolTipText("");

        lblRaizCub.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblRaizCub.setForeground(new java.awt.Color(0, 51, 255));
        lblRaizCub.setToolTipText("");

        lblAbso.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblAbso.setForeground(new java.awt.Color(0, 51, 255));
        lblAbso.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResto)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spnValor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(lblElevado)
                            .addComponent(lblRaizQuad)
                            .addComponent(lblRaizCub)
                            .addComponent(lblAbso))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtResto)
                    .addComponent(txtElevado)
                    .addComponent(txtRaizQuad)
                    .addComponent(txtRaizCub)
                    .addComponent(txtAbso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spnValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtResto)
                            .addComponent(lblResto))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtElevado)
                            .addComponent(lblElevado))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRaizQuad)
                            .addComponent(lblRaizQuad))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRaizCub)
                            .addComponent(lblRaizCub))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAbso)
                            .addComponent(lblAbso))))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int valor = Integer.parseInt(spnValor.getValue().toString());
        int resto = valor % 2;
        float elevado = (float) Math.pow(valor, 3);
        float quad = (float) Math.sqrt(valor);
        float cub = (float) Math.cbrt(valor);
        int abs = (int) Math.abs(valor);
        
        txtResto.setText("Resto da Divisão por 2");
        lblResto.setText(Integer.toString(resto));
        txtElevado.setText("Elevado ao Cubo");
        lblElevado.setText(Float.toString(elevado));
        txtRaizQuad.setText("Raiz Quadrada");
        lblRaizQuad.setText(Float.toString(quad));
        txtRaizCub.setText("Raiz Cúbica");       
        lblRaizCub.setText(Float.toString(cub));
        txtAbso.setText("Valor Absoluto");
        lblAbso.setText(Integer.toString(abs));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperCalculadoraS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperCalculadoraS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperCalculadoraS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperCalculadoraS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuperCalculadoraS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAbso;
    private javax.swing.JLabel lblElevado;
    private javax.swing.JLabel lblRaizCub;
    private javax.swing.JLabel lblRaizQuad;
    private javax.swing.JLabel lblResto;
    private javax.swing.JSpinner spnValor;
    private javax.swing.JLabel txtAbso;
    private javax.swing.JLabel txtElevado;
    private javax.swing.JLabel txtRaizCub;
    private javax.swing.JLabel txtRaizQuad;
    private javax.swing.JLabel txtResto;
    // End of variables declaration//GEN-END:variables
}
